apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
  - name: maven
    image: maven:3.9-eclipse-temurin-17-alpine
    command:
      - cat
    tty: true
  
  - name: licensefinder
    image: licensefinder/license_finder:latest
    command:
      - cat
    tty: true
  
  - name: slscan
    image: shiftleft/scan:latest
    command:
      - cat
    tty: true
  
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - /busybox/cat
    tty: true
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
  
  - name: docker-tools
    image: aquasec/trivy:latest
    command:
      - cat
    tty: true
  
  - name: trufflehog
    image: trufflesecurity/trufflehog:latest
    command:
      - cat
    tty: true
  
  - name: argocd
    image: quay.io/argoproj/argocd:v2.10.0
    command:
      - cat
    tty: true
  
  - name: zap
    image: ghcr.io/zaproxy/zaproxy:stable
    command:
      - sleep
    args:
      - "99999"
    tty: true
  
  volumes:
  - name: docker-config
    secret:
      secretName: docker-credentials
      items:
        - key: .dockerconfigjson
          path: config.json
